name    'inkblot/xl2tpd'
version '1.1.0'
source  'git://github.com/inkblot/puppet-xl2tpd'
author  'inkblot'
license 'Apache 2.0'
summary 'xl2tpd L2TP server'
description 'A puppet module for installing and configuring a xl2tpd L2TP server'
project_page 'https://github.com/inkblot/puppet-xl2tpd'

dependency 'ripienaar/module_data', '>= 0.0.1'
